{
  "formatVersion": "1.0",
  "component": {
    "url": "../../okio-multiplatform/2.4.1/okio-multiplatform-2.4.1.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5.1",
      "buildId": "lusju6lfebb4nedxziisgfxr7q"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.4.1.jar",
          "url": "okio-2.4.1.jar",
          "size": 240710,
          "sha1": "569165a2a9c1f7af07dffc80ed983013a2209896",
          "md5": "600e0004aafd502ccffe1b3e45ff964d"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.4.1.jar",
          "url": "okio-2.4.1.jar",
          "size": 240710,
          "sha1": "569165a2a9c1f7af07dffc80ed983013a2209896",
          "md5": "600e0004aafd502ccffe1b3e45ff964d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.4.1/okio-metadata-2.4.1.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.4.1"
      }
    }
  ]
}
